const motivos = [
    'Você tem um sorriso perfeito',
    'Amo admirar você com aquele sorriso que me encantou desde a primeira vez que te vi...',
    'Amo quando você diz que me ama',
    'Você me dá motivação todos os dias',
    'Amo cada um dos seus traços',
    'Amo a sua voz',
    'Amo cada palavra que sai da sua boca',
    'Amo nossas linguagens do amor',
    'Amo os seus lábios',
    'Eu te amo porque tudo com você tem cor',
    'Você me dá paz',
    'Você me traz felicidade diariamente',
    'Amo seu jeito',
    'Amo a maneira como você fala',
    'Amo ver você feliz',
    'Amo ficar coladinho de você',
    'Você é o meu sonho diário',
    'Você é o meu futuro',
    'Você é engraçada',
    'Amo a forma como você é espetacularmente inteligente',
    'Repetindo... VOCÊ É MUITO INTELIGENTE',
    'Amo o fato de você ser talentosa',
    'Amo ver você tocando sax, violino e qualquer outro instrumento musical que exista...',
    'Amo assistir TV com você',
    'Amo ver filmes e séries com você',
    'Amo ver você com soninho',
    'Amo acordar você com um belo café da manhã',
    'Amo quando você olha pra mim',
    'Amo pegar na sua mão tão macia',
    'Amo te abraçar com toda a força',
    'Você sendo sempre tão sincera comigo',
    'A maneira como posso ser eu mesmo quando estou juntinho de você',
    'Amo conversar com você',
    'Amo a cor do seu cabelo',
    'Amo a cor dos seus olhos',
    'Amo a sua risada tão sincera quando está comigo',
    'Amo o fato de poder ter um futuro inteiro com você',
    'Amo os nossos planos',
    'Amo a maneira como você olha pra mim',
    'Amo te ver cozinhar e poder te ajudar',
    'Amo as suas piadas',
    'Eu amo chorar de felicidade ohando nos seus olhinhos',
    'Amo irritar você KKKKKKK',
    'Amo o fato de você ter trazido a melhor versão de mim',
    'Amo te fazer feliz',
    'Amo o seu strogonoff',
    'Amo tudo aquilo que você cozinha',
    'Amo comer chocolatinhos com você',
    'Amo te contrariar...',
    'Amo a nossa intimidade',
    'Amo poder perguntar como foi o seu dia',
    'Amo estar com você nos nossos sábados e qualquer outro dia possível',
    'Amo não ficar triste quando estou com você',
    'Amo te entregar tudo de mim',
    'Amo quando você me conta sobre o seu dia',
    'Amo ver você dormindo no meu colinho',
    'Amo a sua forma fofa de falar com todos',
    'Amo o jeito como você se veste',
    'Você é extremamente estilosa',
    'Amo as suas roupas',
    'Amo o seu sapatinho rosa KKKKKKKKKKKKKKKKKKKK',
    'Amo a sua camisa do frajola.... KADKADKDAKKDA',
    'Amo cada um dos seus all-star',
    'Amo o seu all-star amarelo, você estava usando ele quando te vi pela primeira vezz',
    'Amo ver você vestida de preto',
    'Amo o seu cheiro',
    'Amo o seu perfume',
    'Amo os creminhos que deixam a sua pele mais macia',
    'Amo fazer massagem em você',
    'Amo te deixar calma',
    'Amo quando você fica mais calma por minha causa',
    'Amo admirar as estrelinhas com você',
    'Amo olhar todo o céu e admirar a natureza ao seu ladinho',
    'Amo o jeito como você dá valor as pequenas coisas',
    'Amo ouvir o seu respirar',
    'Amo saber que você me quer pra todo o sempre',
    'Amo deitar no seu colinho',
    'Amo o fato de ficar admirando o seu rosto e sua beleza incrível',
    'Amo ficar com você da forma mais aconchegante possível',
    'Amo fazer carinho em você',
    'Também amo fazer cócegas em você KKKKKKKK',
    'Amo que você confia em mim',
    'Amo te dar confiança',
    'Amo te emprestar os meus moletons',
    'Também amo te emprestar minhas camisetas KKKKKKKK',
    'Amo o seu respeito por mim',
    'Amo respeitar você',
    'Amo fazer você dar belas risadas',
    'Amo quando você me surpreende',
    'Amo surpreender você',
    'Amo levar você pra lanchar',
    'Amo te dar chocolatinhos',
    'Amo te dar presentes dos mais variados tipos',
    'Amo te fazer surpresas do nosso jeitinho',
    'Amo fofocar com você...',
    'Amo quando a gente se entende só de olhar um para o outro',
    'Amo poder acordar com o seu bom dia',
    'Amo te dar boa noite e dizer que logo estaremos juntinhos...',
    'Amo até a forma como você se espreguiça',
    'AMO VOCÊ DE TODO O MEU CORAÇÃO AAA',
    'Amo o tom da sua risada, sempre tão fofa',
    'Amo a maneira como você tira de mim os mais sinceros sorrisos',
    'Amo comer pipoca com você',
    'Amo aprender com você',
    'Amo te pedir perdão',
    'Amo quando você me perdoa, até porque não sou perfeito',
    'Amo o fato de você cuidar da sua saúde',
    'Amo quando você se preocupa com a minha saúde',
    'Amo almoçar com você',
    'Amo ouvir música com você',
    'Amo te apresentar músicas novas',
    'Amo cantar músicas pra você',
    'Amo tocar violão pra você',
    'Amo tocar guitarra para você',
    'Amo dedicar as mais diversas letras musicais para você',
    'Amo fazer poemas para você',
    'Amo desenhar você e falhar miseravelmente KKKKKKKKK até pq não existe a possibilidade de conseguir abstrair tamanha perfeição em um só papel...',
    'Amo gravar vídeos engraçados para você',
    'Amo gravar áudios falando que te amo',
    'Amo fazer você soltar risadas através dos meus áudios',
    'Amo conquistar as coisas com você',
    'Amo os passos que estamos dando para o nosso futuro',
    'Amo quando você pensa no nosso futuro',
    'Amo acompanhar você em cada nova conquista',
    'Amo caminhar com você',
    'Amo conversar com você os mais variados tipos de assunto',
    'Amo quando você me passa segurança sobre tudo',
    'Amo passar dias chuvosos com você',
    'Amo quando chove bem no nosso sábado, tudo fica mais aconchegante',
    'Amo ver as suas fotinhos antigas KKKKKKKKKK',
    'Amo rir das suas fotinhos antigas',
    'Amo o fato de não me importar muito com a roupa que estou vestindo, até pq namoro com você... A DONA DO MEU CORAÇÃO',
    'Amo ter gostos parecidos com os seus',
    'Amo quando você descansa bastante',
    'Amo quando você está com bastante energia e disposição',
    'Amo quando durmo e sonho com você',
    'Eu amo sonhar com nós dois',
    'Amo os meus sogros',
    'Amo o meu cunhado',
    'Amo os seus parentes',
    'Amo a maneira como cada um da sua família, quer o nosso bem <33',
    'Amo almoços da nossa família',
    'Amo todas as confraternizações da nossa família',
    'Amo a forma como você é simpática com todos a nossa volta',
    'Amo quando você me repreende quando estou fazendo algo errado',
    'Amo a sua simplicidade',
    'Amo a sua humildade',
    'Amo quando vejo você indecisa com algo KKKKKKKK',
    'Amo ficar ansioso com o nosso futuro',
    'Amo quando você fica feliz ao me ver',
    'Você sempre cuida de mim quando estou doentinho',
    'Amo cuidar do seu bem estar',
    'Amo cuidar de você quando está doentinha',
    'Amo cuidar de você em todos os aspectos',
    'Amo cuidar de você pq você é o meu bem mais precioso'
];