const motivos = [
    'Você tem um sorriso perfeito',
    'Amo admirar você com aquele sorriso que me encantou desde a primeira vez que te vi...',
    'Amo quando você diz que me ama',
    'Você me dá motivação todos os dias',
    'Amo cada um dos seus traços',
    'Amo a sua voz',
    'Amo cada palavra que sai da sua boca',
    'Amo nossas linguagens do amor',
    'Amo os seus lábios',
    'Eu te amo porque tudo com você tem cor',
    'Você me dá paz',
    'Você me traz felicidade diariamente',
    'Amo seu jeito',
    'Amo a maneira como você fala',
    'Amo ver você feliz',
    'Amo ficar coladinho de você',
    'Você é o meu sonho diário',
    'Você é o meu futuro',
    'Você é engraçada',
    'Amo a forma como você é espetacularmente inteligente',
    'Repetindo... VOCÊ É MUITO INTELIGENTE',
    'Amo o fato de você ser talentosa',
    'Amo ver você tocando sax, violino e qualquer outro instrumento musical que exista...',
    'Amo assistir TV com você',
    'Amo ver filmes e séries com você',
    'Amo ver você com soninho',
    'Amo acordar você com um belo café da manhã',
    'Amo quando você olha pra mim',
    'Amo pegar na sua mão tão macia',
    'Amo te abraçar com toda a força',
    'Você sendo sempre tão sincera comigo',
    'A maneira como posso ser eu mesmo quando estou juntinho de você',
    'Amo conversar com você',
    'Amo a cor do seu cabelo',
    'Amo a cor dos seus olhos',
    'Amo a sua risada tão sincera quando está comigo',
    'Amo o fato de poder ter um futuro inteiro com você',
    'Amo os nossos planos',
    'Amo a maneira como você olha pra mim',
    'Amo te ver cozinhar e poder te ajudar',
    'Amo as suas piadas',
    'Eu amo chorar de felicidade ohando nos seus olhinhos',
    'Amo irritar você KKKKKKK',
    'Amo o fato de você ter trazido a melhor versão de mim',
    'Amo te fazer feliz',
    'Amo o seu strogonoff',
    'Amo tudo aquilo que você cozinha',
    'Amo comer chocolatinhos com você',
    'Amo te contrariar...',
    'Amo a nossa intimidade',
    'Amo poder perguntar como foi o seu dia',
    'Amo estar com você nos nossos sábados e qualquer outro dia possível',
    'Amo não ficar triste quando estou com você',
    'Amo te entregar tudo de mim',
    'Amo quando você me conta sobre o seu dia',
    'Amo ver você dormindo no meu colinho',
    'Amo a sua forma fofa de falar com todos',
    'Amo o jeito como você se veste',
    'Você é extremamente estilosa',
    'Amo as suas roupas',
    'Amo o seu sapatinho rosa KKKKKKKKKKKKKKKKKKKK',
    'Amo a sua camisa do frajola.... KADKADKDAKKDA',
    'Amo cada um dos seus all-star',
    'Amo o seu all-star amarelo, você estava usando ele quando te vi pela primeira vezz',
    'Amo ver você vestida de preto',
    'Amo o seu cheiro',
    'Amo o seu perfume',
    'Amo os creminhos que deixam a sua pele mais macia',
    'Amo fazer massagem em você',
    'Amo te deixar calma',
    'Amo quando você fica mais calma por minha causa',
    'Amo admirar as estrelinhas com você',
    'Amo olhar todo o céu e admirar a natureza ao seu ladinho',
    'Amo o jeito como você dá valor as pequenas coisas',
    'Amo ouvir o seu respirar',
    'Amo saber que você me quer pra todo o sempre',
    'Amo deitar no seu colinho',
    'Amo o fato de ficar admirando o seu rosto e sua beleza incrível',
    'Amo ficar com você da forma mais aconchegante possível',
    'Amo fazer carinho em você',
    'Também amo fazer cócegas em você KKKKKKKK',
    'Amo que você confia em mim',
    'Amo te dar confiança',
    'Amo te emprestar os meus moletons',
    'Também amo te emprestar minhas camisetas KKKKKKKK',
    'Amo o seu respeito por mim',
    'Amo respeitar você',
    'Amo fazer você dar belas risadas',
    'Amo quando você me surpreende',
    'Amo surpreender você',
    'Amo levar você pra lanchar',
    'Amo te dar chocolatinhos',
    'Amo te dar presentes dos mais variados tipos',
    'Amo te fazer surpresas do nosso jeitinho',
    'Amo fofocar com você...',
    'Amo quando a gente se entende só de olhar um para o outro',
    'Amo poder acordar com o seu bom dia',
    'Amo te dar boa noite e dizer que logo estaremos juntinhos...',
    'Amo até a forma como você se espreguiça',
    'AMO VOCÊ DE TODO O MEU CORAÇÃO AAA',
    'Amo o tom da sua risada, sempre tão fofa',
    'Amo a maneira como você tira de mim os mais sinceros sorrisos',
    'Amo comer pipoca com você',
    'Amo aprender com você',
    'Amo te pedir perdão',
    'Amo quando você me perdoa, até porque não sou perfeito',
    'Amo o fato de você cuidar da sua saúde',
    'Amo quando você se preocupa com a minha saúde',
    'Amo almoçar com você',
    'Amo ouvir música com você',
    'Amo te apresentar músicas novas',
    'Amo cantar músicas pra você',
    'Amo tocar violão pra você',
    'Amo tocar guitarra para você',
    'Amo dedicar as mais diversas letras musicais para você',
    'Amo fazer poemas para você',
    'Amo desenhar você e falhar miseravelmente KKKKKKKKK até pq não existe a possibilidade de conseguir abstrair tamanha perfeição em um só papel...',
    'Amo gravar vídeos engraçados para você',
    'Amo gravar áudios falando que te amo',
    'Amo fazer você soltar risadas através dos meus áudios',
    'Amo conquistar as coisas com você',
    'Amo os passos que estamos dando para o nosso futuro',
    'Amo quando você pensa no nosso futuro',
    'Amo acompanhar você em cada nova conquista',
    'Amo caminhar com você',
    'Amo conversar com você os mais variados tipos de assunto',
    'Amo quando você me passa segurança sobre tudo',
    'Amo passar dias chuvosos com você',
    'Amo quando chove bem no nosso sábado, tudo fica mais aconchegante',
    'Amo ver as suas fotinhos antigas KKKKKKKKKK',
    'Amo rir das suas fotinhos antigas',
    'Amo o fato de não me importar muito com a roupa que estou vestindo, até pq namoro com você... A DONA DO MEU CORAÇÃO',
    'Amo ter gostos parecidos com os seus',
    'Amo quando você descansa bastante',
    'Amo quando você está com bastante energia e disposição',
    'Amo quando durmo e sonho com você',
    'Eu amo sonhar com nós dois',
    'Amo os meus sogros',
    'Amo o meu cunhado',
    'Amo os seus parentes',
    'Amo a maneira como cada um da sua família, quer o nosso bem <33',
    'Amo almoços da nossa família',
    'Amo todas as confraternizações da nossa família',
    'Amo a forma como você é simpática com todos a nossa volta',
    'Amo quando você me repreende quando estou fazendo algo errado',
    'Amo a sua simplicidade',
    'Amo a sua humildade',
    'Amo quando vejo você indecisa com algo KKKKKKKK',
    'Amo ficar ansioso com o nosso futuro',
    'Amo quando você fica feliz ao me ver',
    'Você sempre cuida de mim quando estou doentinho',
    'Amo cuidar do seu bem estar',
    'Amo cuidar de você quando está doentinha',
    'Amo cuidar de você em todos os aspectos',
    'Amo cuidar de você pq você é o meu bem mais precioso',
    'Amo observar e admirar cada detalhe da sua perfeição que é a maior maravilha desse mundo',
    'Amo (mas n me machuca pfvr KKKKK) quando você me dá aquelas mordidinhas',
    'Amo as suas manias',
    'Amo fazer você ficar com as minhas manias',
    'Você enxerga a minha beleza interior',
    'Você também enxerga a minha beleza exterior',
    'Você enxerga tudo de bom que há em mim',
    'Você desperta tudo que existe de feliz em mim',
    'Amo despertar em você a felicidade',
    'Amo alimentar você (que nem criança)',
    'Amo dividir minha comida com você',
    'Amo quando temos tempo de qualidade um com o outro',
    'Amo ter tempo para gastar livremente com você',
    'Amo ligar pra você',
    'Amo ficar em ligação durante horas com você',
    'Amo quando você me liga do nada',
    'Amo te elogiar',
    'Amo exaltar todos as características que fazem de você a mulher mais perfeita desse universo',
    'Amo quando te deixo boba por te elogiar',
    'Amo te chamar de criança e te irritar KKKKKKKK',
    'Amo as nossas piadas internas',
    'Amo quando só a sua presença é o suficiente',
    'Amo quando dizem que eu e você juntos, somos lindos',
    'Amo limpar as suas lágrimas',
    'Amo estar com você e te confortar em momentos tristes',
    'Amo quando você me elogia',
    'Amo quando você elogia a minha roupa',
    'Amo quando você diz que sou inteligente (mesmo sabendo que não sou o inteligente da relação)',
    'Amo rir de você',
    'Amo quando você me diz algo engraçado',
    'Amo gravar videozinhos com você',
    'Amo tirar fotinhos com você',
    'Amo postar fotinhos nossass',
    'Amo ter você só pra mim',
    'Amo poder gritar pra todos que você é só minha',
    'Amo viajar com você',
    'Amo te socorrer quando você não está bem',
    'Amo quando você deita no meu colinho para descansar',
    'Amo comemorar todas as nossas datas especiais, como é o caso da data de hoje <333',
    'Eu adivinho tudo aquilo que você está pensando KKKKKKK',
    'Amo ficar sentadinho no sofá com você',
    'Amo o seu cabelo',
    'Amo quando você se declara pra mim',
    'Amo contar pra todos sobre você',
    'Amo contar pra todos como você é extremamente perfeita linda inteligente e talentosa',
    'Amo tomar aquele cafézinho preto acompanhado daquele pão de queijo com você',
    'Amo ajudar você',
    'Amo ajudar quando você precisa',
    'Amo te auxiliar nas suas indecisões',
    'Amo te motivar para podermos continuar a nossa vida juntos',
    'Amo a data do seu aniversário',
    'Amo as comemorações dos nossos meses de namoro',
    'Amo tirar férias da faculdade e ter mais tempo para você',
    'Amo ficar de folga e aproveitar com você',
    'Amo jogar joguinhos com você',
    'Amo passar qualquer estação de tempo com você',
    'Amo quando estamos juntinhos no inverno',
    'Amo tomar sorvete com casquinha ao seu ladinho',
    'Amo dar água pra você beber e continuar linda e hidratada',
    'Amo ter motivação para continuar acordando e se esforçando pelo nosso futuro',
    'Amo o fato de te conhecer muito bem',
    'Amo adivinhar os seus próximos passos KKKKKKK',
    'Amo planejar os nossos sábados',
    'Amo aproveitar ao máximo cada momento com você',
    'Amo dar sempre o último pedaço de pizza pra você',
    'Eu quero ficar pra sempre com você',
    'Eu tenho a certeza de que quero passar todos os dias da minha vida com você',
    'Amo também as suas piadas sem graça KKKKKKK',
    'Eu gosto quando você ri por educação da minhas piadas sem graça KKKKKK',
    'Amo demonstrar amor de todas as formas possíveis',
    'Amo os presentinhos que você faz para mim com todo amor desse mundo',
    'Amo o fato de sempre quando escuto "Rex Orange", lembro de você',
    'Estou escutando Rex Orange pensando no quanto eu te amo',
    'Você marcou momentos muito especiais na minha vida',
    'Amo te enviar memes',
    'Amo te acompanhar e mostrar pra todos que sou seu',
    'Ainda sinto frio na barriga quando vou te ver',
    'Você é a minha pessoa favorita',
    'Você é a minha outra metade da laranja KKKKKKKKKK',
    'Amo o jeito como você me faz feliz de todas as maneiras possíveis',
    'Amo evoluir a relação juntinho de você',
    'Nascemos um para o outro',
    'Combinamos muito um com o outro',
    'Honestidade sempre é um ponto importante na nossa relação',
    'Amo o fato do nosso amor crescer mais a cada dia que passa',
    'Eu te amo mais a cada dia que passa',
    'Amo quando você opina sobre algo',
    'Amo quando você pede minha opinião sobre algo',
    'Amo o fato de você saber o que eu gosto de vestir',
    'Amo quando você escolhe as minhas roupas',
    'Mesmo que as vezes seja difícil estar longe, nada diminui o nosso amor',
    'A saudade que sinto é uma das coisas que prova o meu amor por você',
    'Amo acordar dps de um sonho que tive com você',
    'Amo encher você de amor e beijinhos',
    'Amo quando você me fala algo inteligente',
    'Amo te incentivar a ter um futuro profissional',
    'Amo entender você',
    'Amo ajudar você a ficar mais tranquila com situações ruins',
    'Amo ser romântico com você',
    'Amo organizar nossos dias',
    'Amo saber que você é toda minha',
    'Amo ter motivos pra sorrir com você',
    'Amo me perder no seu olhar e no seu sorriso',
    'A vida ganha mais sentido tendo você ao meu lado',
    'Somos parceiros um do outro',
    'Discordo só pra incomodar você KKKKKKK',
    'Amo pensar nos presentes que vou te dar',
    'Viajo pensando em você quando estou escutando músicas românticas',
    'Amo que por você eu aceitaria o tipo de vida mais humilde e simples possível',
    'Amo fazer drama pra você',
    'Amo criar algumas suposições com você... (famosas fofocas..)',
    'Você me conhece e sabe quando eu estou com medo',
    'Você me encoraja para ir atrás dos nossos sonhos',
    'Amo o fato de você ser atenciosa',
    'Tenho certeza de que você é o meu amor pra todo o sempre',
    'Você sempre me abraça e cuida de mim quando eu preciso',
    'Você deixa eu entender os seus sentimentos',
    'Você me completa em todos os sentidos',
    'Quero envelhecer juntinho de você',
    'Você é muito carinhosa',
    'Amo ficar bobo quando te vejo',
    'Amo ter paciência com você, pq sim, estou falando com o meu bebê',
    'Nunca pensei que amaria tanto assim como eu te amo',
    'Você me inspira a lutar pelo nosso futuro',
    'Amo o fato de você não querer mudar nada em mim',
    'Amo quando você concorda com muitas loucuras minhas',
    'Amo estar no paraíso (com você)',
    'Amo o fato de você ser única',
    'Amo você sendo compreensiva comigo',
    'Amo quando você abdica de muitas coisas pelo nosso bem',
    'Amo o seu jeito único e especial',
    'Amo quando estou com dor de cabeça e você cuida tão bem de mim',
    'Nunca imaginei amar tanto uma pessoa',
    'Amo quando você cuida até do meu sono e do quanto estou dormindo',
    'Amo saber que você vai virar velhinha e ainda vai continuar sendo a mulher mais perfeita desse mundo',
    'Eu te amo porque quero continuar sendo seu pra todo o sempre',
    'Amo que não sinto falta de mais nada quando estou ao seu ladinho',
    'Amo você porque os problemas são menores estando ao seu ladinho',
    'Amo ser cavalheiro por você',
    'Amo quando te abraço e sinto o seu amor no estado mais puro possível',
    'Amo amarrar o seu calçado',
    'Amo que no fim de cada noite quando tenho que me despedir, sinto mais a sua falta',
    'Quando estou longe de você, segundos são séculos mas quando estou com você, horas são iguais a segundos',
    'Você é a tampa da minha panela (tá, clichêzinho também vale KKKKKKKKKKK)',
    'Amo o fato de não querer mais alguém a não ser você',
    'Amo não estar sozinho, pq tenho você',
    'Amo ver modelos para a nossa casa <3333',
    'Amo sonhar no nosso futura na nosa casa <33',
    'Amo me divertir com você',
    'Amo que em qualquer lugar, nos divertimos com a presença um do outro',
    'Você nunca vai desistir de mim, apesar dos meus defeitos',
    'Amo te tratar como a minha jóia rara',
    'A vida sem você não teria graça',
    'A vida sem você não teria sentido nenhum',
    'Amo dividir momentos com você',
    'Amo me sentir burro vendo você falar coisas super inteligentes',
    'Amo o fato de você ser especial para mim',
    'Meu coração fica quentinho quando penso em você',
    'Amo saber que você é tudo que eu mais preciso',
    'Amo dizer que te amo o tempo todo',
    'Amo saber que todo esse nosso amor, é real',
    'Amo o fato de dizer que sou perfeito, mesmo sabendo que não sou',
    'Amo falar que te amo no seu ouvidinho',
    'Amo quando você fala no meu ouvidinho',
    'Amo saber que vou ter uma família com você',
    'Quero muito construir uma família linda ao seu ladinho',
    'Amo querer ganhar dinheiro para te dar mais presentinhos',
    'Amo que sem você eu me torno incompleto',
    'Amo te dar beijinhos na testa',
    'Amo também te dar beijinhos na bochecha',
    'Amo que quero descobrir tudo sobre você',
    'Amo te conhecer cada dia mais',
    'Você é extremamente maravilhosa',
    'Você é incrívelmente incrível',
    'Você me dá segurança e não vai fazer eu me machucar',
    'Amo quando você se faz de forte (e é forte mesmo)',
    'Amo deixar você fazer parte da minha vida',
    'Mesmo cansada, me trata como príncipe',
    'Amo te tratar como minha princesa encantada, tudo pra mim',
    'Amo quando você se preocupa comigo',
    'Amo a sua responsbilidade com tudo',
    'Amo que você me deixa louco de saudade o tempo todo',
    'Meu coração dispara sempre quando te vejo',
    'Vivo um sonho com você',
    'Amo imaginar viver uma vida inteira ao seu lado',
    'Você me conquista a cada novo dia que passa',
    'Você ama os meus cachinhos',
    'Você gosta das mesmas coisas que eu',
    'Amo você quando me perdoa',
    'Amo porque o meu amor pra sempre será só seu',
    'Amo comemorar o dia 24 com você <333',
    'Amo o fato de você ser minha prioridade',
    'Você é a minha alma gêmea',
    'Amo conseguir te amar naturalmente',
    'Amo me perder no seu olhar magnífico',
    'Amo ouvir todas as suas palavras lindas a respeito de mim',
    'Amo não existir menor possibilidade de amar outra pessoa a não ser você',
    'Amo ter você como rainha da minha vida',
    'Amo fazer aviãozinho pra você quando não quer comer algo',
    'Amo te fazer promessas sobre o nosso futuro principalmente',
    'Amo que você me entende',
    'Amo cuidar de você, amar você, guardar você no meu coração e te valorizar como merece',
    'Amo estar apaixonado por você',
    'Eu amo as coisas que você me diz sobre o nosso futuro',
    'Como diria o cantor de Rex Orange, "you save me"',
    'Amo o seu all-star amarelo acompanhado do seu sorriso radiante (primeira vez que te vi... nunca vou superar)',
    'Amo o fato de saber que 1 ano atrás, tomei a melhor decisão da minha vida <3',
    'De todos esses meses com você, tenho a plena certeza de que faria tudo de novo porque eu simplesmente...',
    'Amo te amar <3',
];